<a href="https://colab.research.google.com/github/durgaprasadnagireddy6655-commits/Daily-Activities/blob/main/numpy%20day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
l=range(100)
%timeit [i**2 for i in l]# used to calculate the time for each iteration


4.36 µs ± 1.23 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


**creating arrays**


In [6]:
a=np.array([1,2,3,4,5])
print(a.ndim)

1


In [7]:
b=np.array([[1,2,3],[4,5,6]])
print(b.ndim)
print(b)

2
[[1 2 3]
 [4 5 6]]


In [8]:
c=np.array([[[1,2],[3,4],[5,6]]])
print(c.ndim)
print(c)

3
[[[1 2]
  [3 4]
  [5 6]]]


In [9]:
c=np.array([[[1,2],[2,3]],[[4,5],[6,7]]])
print(c)

[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]]


In [10]:
print(c.ndim)

3


In [11]:
print(c.shape)

(2, 2, 2)


In [12]:
print(a.shape)

(5,)


In [13]:
print(b.shape)

(2, 3)


**Functions for creating array**

In [14]:
a=np.arange(1,10,2)# give the jump values
print(a)

[1 3 5 7 9]


In [15]:
a=np.linspace(0,1,5)# using display 5 values
print(a)


[0.   0.25 0.5  0.75 1.  ]


In [16]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
a=np.eye(4,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [21]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
print(np.diag(a))

[1 2 3 4]


**Basic data types**

In [23]:
a=np.arange(10)
print(a.dtype)

int64


In [24]:
a = np.arange(10,dtype="float64")
print(a.dtype)

float64


In [25]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


**other datatype**

In [26]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [27]:
a=np.array([True,False])
print(a.dtype)

bool


In [28]:
a=np.array(["niha","Nihas"])
print(a.dtype) #unicode string type

<U5


**indexing and slicing**

In [29]:
a=np.arange(10)
print(a[5])

5


In [30]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [31]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [32]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
print(a[1:8:2])

[1 3 5 7]


In [34]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [35]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [36]:
print(np.shares_memory(a,b))

True


In [37]:
b[0]=10 #viewing
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [39]:
a=np.arange(10)
b=a[::2].copy() #force a copy
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [42]:
print(np.shares_memory(a,b))

False


**Random number genarator**

In [43]:
a=np.random.randint(0,20,15)
print(a)

[18  6 15 10  2  6 15  6 10 15 18 16 15 13  2]


In [44]:
mask=(a%2==0)

In [45]:
mask_a = a[mask]
print(mask_a)

[18  6 10  2  6  6 10 18 16  2]


In [46]:
a[mask]=-1
print(a)

[-1 -1 15 -1 -1 -1 15 -1 -1 15 -1 -1 15 13 -1]
